#parallel_main:
#g++ src/component.cpp src/node.cpp src/scanner.cpp src/functions.cpp src/main.cpp -o bin/TspPar -fopenmp -Wall -pedantic
parallel_mainExec:
g++ /src/component.cpp /src/node.cpp /src/scanner.cpp /src/functions.cpp /src/mainExec.cpp -o /bin/TspPar -fopenmp -Wall -pedantic
